# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTgddinternetviettel():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_tgddinternetviettel(self):
        self.driver.get("https://www.thegioididong.com/tien-ich/thanh-toan-internet-viettel/")
        self.driver.set_window_size(1920, 1053)
        self.driver.find_element(By.ID, "txtUserCode").click()
        self.driver.find_element(By.ID, "txtUserCode").send_keys("t008_gftth_oanhv0")
        self.driver.find_element(By.CSS_SELECTOR, ".checkpay").click()
        total = self.driver.find_element(By.ID, "totalp")
        print('total', total.text)

def main():
    test = TestTgddinternetviettel()
    test.test_tgddinternetviettel()

if __name__ == '__main__':
    main()